using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.GameObjects;
using Robust.Shared.Graphics;
using Robust.Shared.IoC;
using Robust.Shared.Utility;

namespace Content.Client.UserInterface.Systems.RT.Widgets;

[GenerateTypedNameReferences]
public sealed partial class RTVitalBarsHud : UIWidget
{
    private bool _iconsLoaded;

    public RTVitalBarsHud()
    {
        RobustXamlLoader.Load(this);

        var track = new StyleBoxFlat { BackgroundColor = Color.FromHex("#1e1e24") };
        RTHealthBar.BackgroundStyleBoxOverride = track;
        RTHealthBar.ForegroundStyleBoxOverride = new StyleBoxFlat { BackgroundColor = Color.FromHex("#d32f2f") };
        RTStaminaBar.BackgroundStyleBoxOverride = track;
        RTStaminaBar.ForegroundStyleBoxOverride = new StyleBoxFlat { BackgroundColor = Color.FromHex("#388e3c") };
    }

    /// <summary>
    /// RSI icons need <see cref="SpriteSystem"/>; screens are constructed in UI PostInitialize before entity systems exist.
    /// </summary>
    public void EnsureIconsLoaded()
    {
        if (_iconsLoaded)
            return;

        var entManager = IoCManager.Resolve<IEntityManager>();
        if (!entManager.TrySystem(out SpriteSystem? sprites))
            return;

        _iconsLoaded = true;
        RTHealthIcon.Texture = sprites.Frame0(new SpriteSpecifier.Rsi(
            new ResPath("/Textures/Interface/Alerts/human_alive.rsi"), "health0"));
        RTStaminaIcon.Texture = sprites.Frame0(new SpriteSpecifier.Rsi(
            new ResPath("/Textures/Interface/Alerts/stamina.rsi"), "stamina0"));
    }
}
